---
class: 4
flags: 0x0000
unid: OF83B272C07A90AE3E-ON004AA3F38525896C
items:
  - name: $$ScriptName
    type: text
    data: dlgConfig
    signed: true
    nonsummary: true
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $Fields
    type: text
    data: []
  - name: $Flags
    type: text
    data: ""
  - name: $Script
    type: text
    data: |
      '++LotusScript Development Environment:2:5:(Options):0:66
      Option Public
      Option Explicit 
      Use "BSXnotesUtilsUI" 
      
      '++LotusScript Development Environment:2:5:(Forward):0:1
      
      '++LotusScript Development Environment:2:5:(Declarations):0:2
      Const FORM_PREFIX = |DIALOG FORM: dlgConfig.|
    signed: true
    nonsummary: true
  - name: $SubForm_RepIDs
    type: text
    data: "0000000000000000"
    signed: true
  - name: $TITLE
    type: text
    data:
      - (dlgConfig)
      - dlgConfig
    signed: true
  - name: $Body
    type: composite
    signed: true
    nonsummary: true
    data:
      - type: 0x0081
      - type: 0xff82
        FirstLineLeftMargin: 1440
        Flags: 0x8100
        Flags2: 0x8095
        JustifyMode: 0
        LeftMargin: 1440
        LineSpacing: 0
        PABID: 1
        ParagraphSpacingAfter: 0
        ParagraphSpacingBefore: 0
        RightMargin: 0
        Tab:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        TabTypes: 0x00000000
        Tabs: 0
        data:
          - 1440
          - 12
          - 1440
          - 12
          - 12240
          - 100
          - 0x00000001
          - 0x00000006
      - type: 0x0083
        PABID: 1
      - type: 0x00dd
        Signature: 0xff85
        Version: 0
      - type: 0xff85
        FontID: 0x8090001
      - type: 0x00d2
        Color:
          Flags: 0x0001
          rgb: 0x008000
      - type: 0x00de
        Signature: 0xff85
        Version: 0
      - type: 0x0081
      - type: 0xff82
        FirstLineLeftMargin: 1440
        Flags: 0x0100
        Flags2: 0x0794
        JustifyMode: 0
        LeftMargin: 1440
        LineSpacing: 0
        PABID: 2
        ParagraphSpacingAfter: 0
        ParagraphSpacingBefore: 0
        RightMargin: 0
        Tab:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        TabTypes: 0x00000000
        Tabs: 0
        data:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
      - type: 0x0083
        PABID: 2
      - type: 0xfffb
        opaque: +/8sAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAA=
      - type: 0x00a3
        opaque: ow6gBSgAPAAAAAAAAgA=
      - type: 0x00a4
        opaque: pBIAAKAF+CUAAAACAAABAQAA
      - type: 0x0081
      - type: 0xff82
        FirstLineLeftMargin: 1545
        Flags: 0x8186
        Flags2: 0x8055
        JustifyMode: 0
        LeftMargin: 1545
        LineSpacing: 0
        PABID: 3
        ParagraphSpacingAfter: 0
        ParagraphSpacingBefore: 0
        RightMargin: 9630
        Tab:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        TabTypes: 0x00000000
        Tabs: 0
        data:
          - 90
          - 0
          - 90
          - 0
          - 8190
          - 100
          - 0x00000001
          - 0x00000006
      - type: 0x0083
        PABID: 3
      - type: 0x00dd
        Signature: 0xff85
        Version: 0
      - type: 0xff85
        FontID: 0x8090001
      - type: 0x00d2
        Color:
          Flags: 0x0001
          rgb: 0x008000
      - type: 0x00de
        Signature: 0xff85
        Version: 0
      - type: 0x0081
      - type: 0x0083
        PABID: 3
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x00dd
        Signature: 0xffad
        Version: 0
      - type: 0xff71
        opaque: |
          cf9GAAAAAAADABgAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAENvbmZpZ1xUb29sa2l0SW5mbyB8IGNmZy1U
          b29sa2l0SW5mbw==
      - type: 0xffad
        opaque: rf8xAA4ACAAAACUAQ29uZmlnXFRvb2xraXRJbmZvIHwgY2ZnLVRvb2xraXRJbmZvAA==
      - type: 0x00ae
        opaque: rgI=
      - type: 0x00de
        Signature: 0x00ae
        Version: 0
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0x0083
        PABID: 3
      - type: 0x00dd
        Signature: 0xff85
        Version: 0
      - type: 0xff85
        FontID: 0x8090001
      - type: 0x00d2
        Color:
          Flags: 0x0001
          rgb: 0x008000
      - type: 0x00de
        Signature: 0xff85
        Version: 0
      - type: 0x00a5
        opaque: pQYAAAAA
      - type: 0x0081
      - type: 0x0083
        PABID: 1
      - type: 0x00dd
        Signature: 0xff85
        Version: 0
      - type: 0xff85
        FontID: 0x8090001
      - type: 0x00d2
        Color:
          Flags: 0x0001
          rgb: 0x008000
      - type: 0x00de
        Signature: 0xff85
        Version: 0
      - type: 0x0081
      - type: 0x0083
        PABID: 1
      - type: 0x00dd
        Signature: 0xff85
        Version: 0
      - type: 0xff85
        FontID: 0x8090001
      - type: 0x00d2
        Color:
          Flags: 0x0001
          rgb: 0x008000
      - type: 0x00de
        Signature: 0xff85
        Version: 0
  - name: $HTMLCode
    signed: true
    nonsummary: true
    type: opaque
    type_num: 1
    opaque: X/8QAAIADwAHAAAAAAAAAA==
  - name: $Info
    signed: true
    nonsummary: true
    type: opaque
    type_num: 1
    opaque: hhgAAIAAAAAAgAAAAAAJAAAAAAAQAAAA
remaining: []