---
ACL:
  opaque: |
    Q0ECACYMCgAAAAAAUABgBRAAYAqACgEAAAAoAAUAAAAEgCgALwUUADAyLzIxLzIwMjQgMTE6NDY6Mzcg
    QU0gRGV2aW4gT2xzb24vVVNBL1BOUEhDTCB1cGRhdGVkIExhYiBSYXRzIEVkaXRvcnMAMDIvMDkvMjAy
    NCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9VU0EvUE5QSENMIHVwZGF0ZWQgc2FnZS9oY2xsYWJzADAy
    LzA5LzIwMjQgMDQ6NDg6MjEgUE0gRGV2aW4gT2xzb24vVVNBL1BOUEhDTCBhZGRlZCBzYWdlL2hjbGxh
    YnMAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9VU0EvUE5QSENMIGFkZGVkIExvY2Fs
    RG9tYWluU2VydmVycwAwMi8wOS8yMDI0IDA0OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wg
    YWRkZWQgTG9jYWxEb21haW5BZG1pbnMAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9V
    U0EvUE5QSENMIGFkZGVkIExhYiBSYXRzIEVkaXRvcnMAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBEZXZp
    biBPbHNvbi9VU0EvUE5QSENMIGFkZGVkIEFub255bW91cwAwMi8wOS8yMDI0IDA0OjQ4OjIxIFBNIERl
    dmluIE9sc29uL1VTQS9QTlBIQ0wgYWRkZWQgUm9ja3kgT2xpdmVyL1VTQS9QTlBIQ0wAMDIvMDkvMjAy
    NCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9VU0EvUE5QSENMIGFkZGVkIERldmluIE9sc29uL1VTQS9Q
    TlBIQ0wAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9VU0EvUE5QSENMIGFkZGVkIEJv
    YiBCYWxhYmFuL1VTQS9QTlBIQ0wAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBEZXZpbiBPbHNvbi9VU0Ev
    UE5QSENMIGFkZGVkIFBhdWwgV2l0aGVycy9VSy9QTlBIQ0wAMDIvMDkvMjAyNCAwNDo0ODoyMSBQTSBE
    ZXZpbiBPbHNvbi9VU0EvUE5QSENMIHVwZGF0ZWQgLURlZmF1bHQtADAyLzA5LzIwMjQgMDQ6NDg6MjEg
    UE0gRGV2aW4gT2xzb24vVVNBL1BOUEhDTCB1cGRhdGVkIHJvbGUgW0FkbWluXQAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAwMi8wOS8yMDI0IDA0
    OjQ4OjIxIFBNIERldmluIE9sc29uL1VTQS9QTlBIQ0wgZGVsZXRlZCByb2xlIAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAEFkbWluAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAJ4KAAAAANIKBgsAAG4LAAAAAIwLAADYCwAAAAwAAAAAAABFQQQAIAAAAAAA
    AAAAAAQGCQAtRGVmYXVsdC0AAABFQQYAIAAAAAAAAAAAALgHHgBDTj1QYXVsIFdpdGhlcnMvT1U9VUsv
    Tz1QTlBIQ0wAAAAARUEGACAAAAAAAAAAAAC4Bx4AQ049Qm9iIEJhbGFiYW4vT1U9VVNBL089UE5QSENM
    AAAAAEVBBgAgAAAAAAAAAAAAuAceAENOPURldmluIE9sc29uL09VPVVTQS9PPVBOUEhDTABCAABFQQYA
    IAAAAAAAAAAAALgHHwBDTj1Sb2NreSBPbGl2ZXIvT1U9VVNBL089UE5QSENMADoLRUEAAAAAAAAAAAAA
    AAAFAAkAQW5vbnltb3VzAAAARUEEACAAAAAAAAAAAABgBhAATGFiIFJhdHMgRWRpdG9ycwAAAABFQQYA
    AAAAAAAAAAAAAPgHEQBMb2NhbERvbWFpbkFkbWlucwCyC0VBBgAAAAAAAAAAAAAA2gcSAExvY2FsRG9t
    YWluU2VydmVycwAAAABFQQYAAAAAAAAAAAAAAJqHEQBDTj1zYWdlL089aGNsbGFicwA=
DBOptions: 0x00000020
DBInfo:
  FTIndexPriority: 3
  FTOptions: 0x0044
  FTStopFile: ""
  FTThesaur: ""
  Flags: 0x0000
  MajorVersion: 1
  MinorVersion: 0
  Options: 0x0000
  Spare1: 0