---
class: 512
flags: 0x0000
unid: OFAECCC4A4F8344D54-ON0038514180258939
items:
  - name: $AssistAction
    type: action
    code_type: 65413
    data: |
      '++LotusScript Development Environment:2:5:(Options):0:74
      %REM
      	Agent Log Config
      	Created Nov 28, 2010 by Devin Olson/azlighthouse
      	Opens the Log Config document for editing. 
      %END REM
      Option Public
      Option Explicit
      Use "enhLogClassLite"
      
      
      '++LotusScript Development Environment:2:5:(Forward):0:1
      Declare Sub Initialize()
      
      '++LotusScript Development Environment:2:5:(Declarations):0:2
      
      '++LotusScript Development Environment:2:2:Initialize:3:10
      
      
      Sub Initialize()
      	Dim extendedInfo As String
      	On Error Goto ErrorTrap
      	
      	Dim nuiwsp As New NotesUIWorkspace()
      	Dim ndoc As NotesDocument
      	
      	enhLogSetLogStackExceptions True
      	
      	Set ndoc = enhLogGetLogConfigDoc(True)
      	If (ndoc Is Nothing) Then Goto ExitPoint
      
      	Call nuiwsp.EditDocument(False, ndoc)
      	
      ExitPoint:
      	Exit Sub
      ErrorTrap:
      	On Error Goto 0
      	enhLogException ||, extendedInfo$
      	Messagebox Error() & Chr(10) & extendedInfo$ & Chr(10) & |Please consult the log for additional information.|, 16, |Error #| & Cstr(Err())
      	Resume ExitPoint	
      End Sub
    dwFlags: 0x00000000
    signed: true
    nonsummary: true
  - name: $AssistDocCount
    type: number
    data: 0
    signed: true
  - name: $AssistFlags
    type: text
    data: Es
    signed: true
  - name: $AssistInfo
    type_num: 17
    type: opaque
    opaque: |
      AQAEAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    signed: true
    nonsummary: true
  - name: $AssistLastRun
    type: time
    signed: true
  - name: $AssistQuery
    type_num: 15
    type: opaque
    opaque: gQYAAAAA
    signed: true
    nonsummary: true
  - name: $AssistRunInfo
    type: object
    obj_type: 0x0008
    obj_class: 0x0200
    obj_privs: 0x0000
    opaque: |
      AAAAAAUAAAAwAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAwsZYAPuKJYUAAAAA
      /KtYAPuKJYUMq1gA+4olhQAAAAAAAAAAAAAAAAAAAAAAAAAAU3RhcnRlZCBydW5uaW5nIGFnZW50ICdU
      b29sc1xMb2cgQ29uZmlnfHVpLU9wZW5Mb2dDb25maWcnIG9uIDA0LzEwLzIwMjQgMTI6MDk6NDAgUE0N
      ClJhbiBMb3R1c1NjcmlwdCBjb2RlDQpEb25lIHJ1bm5pbmcgYWdlbnQgJ1Rvb2xzXExvZyBDb25maWd8
      dWktT3BlbkxvZ0NvbmZpZycgb24gMDQvMTAvMjAyNCAxMjowOTo0MCBQTQ0KAA0KiUwIHqNWlnKWxlgA
      +4olhaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
      qqqqqqqqqqqqqqqq
  - name: $AssistTrigger
    type: text
    data: "4"
  - name: $AssistType
    type: number
    data: 65413
    signed: true
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $Flags
    type: text
    data: 3fL
  - name: $FlagsExt
    type: text
    data: ""
    signed: true
  - name: $POID
    type: time
    data: "2021-12-10T11:40:38.37-05:00"
  - name: $Restricted
    type: number
    data: 1
    signed: true
  - name: $TITLE
    type: text
    data: "Tools\\Log Config|ui-OpenLogConfig"
    signed: true
remaining: []