---
class: 4
flags: 0x0000
unid: OFA1BEB025DA10DA3B-ON00011F3A8525663C
items:
  - name: $$FormScript
    type: text
    data: |
      '++LotusScript Development Environment:2:5:(Options):0:66
      Option Explicit 
      
      '++LotusScript Development Environment:2:5:(Forward):0:1
      Declare Sub Querysave(Source As Notesuidocument, Continue As Variant)  
      
      '++LotusScript Development Environment:2:5:(Declarations):0:2
      
      '++LotusScript Development Environment:2:2:Querysave:1:12
      Sub Querysave(Source As Notesuidocument, Continue As Variant)  
      	On Error Goto ErrorTrap 
      	
      	Call Source.FieldSetText("F_ConfigID", Source.Document.UniversalID)          
      	
      	Continue = True 
      	
      ExitPoint: 
      	Exit Sub 
      ErrorTrap:
      	On Error Goto 0
      	Continue = False 
      	Messagebox Error$(), WIZARD_ERR, |Failed to Save document| 
      	enhLogException FORM_PREFIX, ||
      	Resume ExitPoint
      End Sub
      '++LotusScript Development Environment:2:2:BindEvents:1:129
      Private Sub BindEvents ( Byval ObjectName_ As String )
      	Static Source As NOTESUIDOCUMENT
      	Set Source = Bind(Objectname_)
      	On Event QUERYSAVE From Source Call QUERYSAVE
      End Sub
    signed: true
    nonsummary: true
  - name: $$ScriptName
    type: text
    data: Toolkit Configuration
    signed: true
    nonsummary: true
  - name: $DesignerVersion
    type: text
    data: 8.5.3
  - name: $Fields
    type: text
    data: []
  - name: $Flags
    type: text
    data: CD
  - name: $Script
    type: text
    data: |
      '++LotusScript Development Environment:2:5:(Options):0:66
      Option Public
      Option Explicit 
      Use "BSXNotesUtilsUI" 
      
      
      
      '++LotusScript Development Environment:2:5:(Forward):0:1
      
      '++LotusScript Development Environment:2:5:(Declarations):0:2
      Const FORM_PREFIX = |FORM: ToolkitConfiguration.|
    signed: true
    nonsummary: true
  - name: $SubForm_RepIDs
    type: text
    data:
      - "0000000000000000"
      - "0000000000000000"
    signed: true
  - name: $TITLE
    type: text
    data:
      - "(99. Admin\\02. Toolkit Configuration)"
      - Toolkit Configuration
    signed: true
  - name: $WindowTitle
    type: formula
    data: "\"Toolkit Configuration\""
    opaque: IgAAACAAAQAVAFRvb2xraXQgQ29uZmlndXJhdGlvbgADAA==
    signed: true
    nonsummary: true
  - name: enhLogPurgeAge
    type: number
    data: 0
    nonsummary: true
  - name: $Body
    type: composite
    signed: true
    nonsummary: true
    data:
      - type: 0x0081
      - type: 0xff82
        FirstLineLeftMargin: 1440
        Flags: 0x8100
        Flags2: 0x8095
        JustifyMode: 0
        LeftMargin: 1440
        LineSpacing: 0
        PABID: 1
        ParagraphSpacingAfter: 0
        ParagraphSpacingBefore: 0
        RightMargin: 0
        Tab:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        TabTypes: 0x00000000
        Tabs: 0
        data:
          - 1440
          - 12
          - 1440
          - 12
          - 12240
          - 100
          - 0x00000001
          - 0x00000006
      - type: 0x0083
        PABID: 1
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0x0083
        PABID: 1
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x00dd
        Signature: 0xffad
        Version: 0
      - type: 0xff71
        opaque: |
          cf9YAAAAAAADABgANgAAAAAAAAAAAAAAAAAAAAAAAAAAAE5vdGVzXFN0YW5kYXJkIEZvcm0gQnV0dG9u
          cyB8IG5vdGVzU3RhbmRhcmRGb3JtQnV0dG9ucw==
      - type: 0xffad
        opaque: |
          rf9DAA4ACAAAADcATm90ZXNcU3RhbmRhcmQgRm9ybSBCdXR0b25zIHwgbm90ZXNTdGFuZGFyZEZvcm1C
          dXR0b25zAA==
      - type: 0x00ae
        opaque: rgI=
      - type: 0x00de
        Signature: 0x00ae
        Version: 0
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0xff82
        FirstLineLeftMargin: 1440
        Flags: 0x0100
        Flags2: 0x8094
        JustifyMode: 0
        LeftMargin: 1440
        LineSpacing: 0
        PABID: 2
        ParagraphSpacingAfter: 0
        ParagraphSpacingBefore: 0
        RightMargin: 0
        Tab:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        TabTypes: 0x00000000
        Tabs: 0
        data:
          - 1440
          - 12
          - 1440
          - 12
          - 12240
          - 100
          - 0x00000001
          - 0x00000004
      - type: 0x0083
        PABID: 2
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0x0083
        PABID: 2
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x00dd
        Signature: 0xffad
        Version: 0
      - type: 0xff71
        opaque: |
          cf9GAAAAAAADABgAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAENvbmZpZ1xUb29sa2l0SW5mbyB8IGNmZy1U
          b29sa2l0SW5mbw==
      - type: 0xffad
        opaque: rf8xAA4ACAAAACUAQ29uZmlnXFRvb2xraXRJbmZvIHwgY2ZnLVRvb2xraXRJbmZvAA==
      - type: 0x00ae
        opaque: rgI=
      - type: 0x00de
        Signature: 0x00ae
        Version: 0
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0x0083
        PABID: 1
      - type: 0xff85
        FontID: 0xa000001
      - type: 0x0081
      - type: 0x0083
        PABID: 1
      - type: 0xff85
        FontID: 0xa000001
  - name: $HTMLCode
    signed: true
    nonsummary: true
    type: opaque
    type_num: 1
    opaque: X/8QAAIADwAHAAAAAAAAAF//EAABANAAAgAAAAAAAAA=
  - name: $Info
    signed: true
    nonsummary: true
    type: opaque
    type_num: 1
    opaque: hhgBAIAAAAAAgAAAAQABAP///wAAAAAA
remaining: []