name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy docs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      # Build and publish the site
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # Install python pre-reqs
      - name: Install Mkdocs and pre-reqs
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mike mkdocs-markdownextradata-plugin mkdocs-git-authors-plugin mkdocs-blog-plugin mkdocs-section-index
      # Do the actual deployment
      - name: Deploy GH Pages
        run: |
          mkdocs gh-deploy --force